-- ========================================
-- RAW_CONTACTS (staging table)
-- ========================================
CREATE TABLE IF NOT EXISTS RAW_CONTACTS (
    RAW_ID INT AUTOINCREMENT PRIMARY KEY,
    FULL_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    ORG_NAME STRING,
    ORG_TYPE STRING,
    ROLE_TITLE STRING,
    LOCATION_CITY STRING,
    LOCATION_COUNTRY STRING,
    SOURCE STRING,
    RAW_URL STRING,
    SCRAPED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ========================================
-- CONTACTS (clean, deduped contacts)
-- ========================================
CREATE TABLE IF NOT EXISTS CONTACTS (
    CONTACT_ID INT AUTOINCREMENT PRIMARY KEY,
    FULL_NAME STRING,
    EMAIL STRING UNIQUE,
    PHONE STRING,
    LOCATION_CITY STRING,
    LOCATION_COUNTRY STRING,
    NATIONAL_OR_INTERNATIONAL STRING,
    PRIMARY_LANGUAGE STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ========================================
-- ORGANIZATIONS (labels, radio, blogs, venues)
-- ========================================
CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
    ORG_ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING,
    ORG_TYPE STRING,
    WEBSITE STRING,
    COUNTRY STRING,
    CITY STRING
);


